name: Build and deploy JAR app to Azure Web App - BillingService

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Test PostgreSQL connections
        run: |
          echo "Testing Google Cloud DB"
          PGPASSWORD=a8d.JFvMvBQfcB{b psql -h 34.16.21.44 -p 5432 -U postgres -d BillingService -c '\conninfo'
        shell: bash

      - name: Build with Maven
        run: mvn clean install -Dspring.profiles.active=prod
        working-directory: ./MAINET1.0

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: './MAINET1.0/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'modernsoutions'        # your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # use publish profile secret
          package: './java-app/MAINET1.0-0.0.1-SNAPSHOT.jar'    # path to built JAR
