name: Build and Deploy Spring Boot JAR to Azure Web App - modernsoutions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Step 3: Build Spring Boot JAR
      - name: Build project with Maven
        run: mvn clean package -Dspring.profiles.active=prod
        working-directory: ./MAINET1.0

      # Step 4: Upload JAR artifact for deployment
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-jar-artifact
          path: MAINET1.0/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 5: Download artifact from build
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-jar-artifact
          path: ./artifact

      # Step 6: Verify that the JAR exists
      - name: List downloaded files
        run: ls -R ./artifact

      # Step 7: Azure login
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 8: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'modernsoutions'
          resource-group-name: 'ApplicationServer'
          package: './artifact/*.jar'
          slot-name: 'production'
          startup-command: 'java -jar /home/site/wwwroot/MAINET1.0-0.0.1-SNAPSHOT.jar'
